---
- tags: [preinstall]
  block:
    - ansible.builtin.include_role:
        name: repository
      vars:
        repos_enabled: [opennebula]
      when: opennebula_repo is undefined

    - name: Install OneFlow Server and dependencies
      ansible.builtin.package:
        name: "{{ _common + _specific[ansible_os_family] }}"
      vars:
        _common: [opennebula-flow]
        _specific:
          Debian: []
          RedHat: []
      register: package
      until: package is success
      retries: 12
      delay: 5

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/config.yml"

- ansible.builtin.include_role:
    name: opennebula/leader
  when: leader is undefined

- name: Enable OneFlow Server (NOW)
  ansible.builtin.service:
    name: opennebula-flow
    enabled: true

- when: inventory_hostname == leader
  block:
    - name: Start OneFlow Server (NOW)
      ansible.builtin.service:
        name: opennebula-flow
        state: started
      register: service

    - name: Make sure OneFlow Server is not restarted twice
      ansible.builtin.set_fact:
        flow_no_restart: >-
          {{ service is changed }}
