---
- name: Compute helper facts
  ansible.builtin.set_fact:
    ds_names: >-
      {{ _items | map(attribute='key') | list }}
    ds_dict: >-
      {{ _items | items2dict }}
  vars:
    _ds: >-
      {{ ds_defaults | combine(ds, recursive=true) }}
    _items: >-
      {{ _ds | dict2items
             | map(attribute='value')
             | map('dict2items')
             | flatten
             | selectattr('value.managed', 'true')
             | list }}
  run_once: true

- name: Ensure /var/lib/one/datastores/ exists
  ansible.builtin.file:
    path: /var/lib/one/datastores/
    state: directory
    owner: oneadmin
    group: oneadmin
    mode: u=rwx,go=rx

- name: Setup datastore symlinks
  ansible.builtin.file:
    src: "{{ _src }}/"
    dest: "{{ _dest }}"
    state: link
    owner: oneadmin
    group: oneadmin
    mode: u=rwx,go=rx
  when: inventory_hostname in _hosts and _src != '/var/lib/one/datastores'
  vars:
    _src: >-
      {{ ds_dict[item].symlink.src | realpath }}
    _dest: >-
      /var/lib/one/datastores/{{ ds_dict[item].id }}
    _hosts: >-
      {{ ds_dict[item].symlink.groups | map('extract', groups)
                                      | flatten
                                      | unique
                                      | list }}
  loop: "{{ ds_names }}"
