---
- when: ensure_keys_for is sequence and ensure_keys_for | length > 0
  vars:
    # Skip creating keypairs on hypervisor nodes as they are unneeded/unused (non-HCI).
    _groups: >-
      {{ groups.keys() | difference([node_group | d('node'), 'all', 'ungrouped']) }}
    # Extract all hosts selected for private key generation.
    _hosts: >-
      {{ _groups | map('extract', groups)
                 | flatten
                 | unique
                 | intersect(ansible_play_hosts) }}
  block:
    - name: Create id_rsa/.pub keypairs
      community.crypto.openssh_keypair:
        path: "~{{ item.1 }}/.ssh/id_rsa"
        type: rsa
        size: "{{ rsa_key_size }}"
        owner: "{{ item.1 }}"
        mode: u=rw,go=
        regenerate: never
        force: false
      loop: >-
        {{ [inventory_hostname] | product(ensure_keys_for) }}
      when:
        - inventory_hostname in _hosts
      register: keypair

    - name: Add authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.item.1 }}"
        key: "{{ item.public_key }}"
      loop: "{{ _items }}"
      vars:
        _results: >-
          {{ _hosts | map('extract', hostvars, ['keypair', 'results']) | flatten }}
        _items: >-
          {{ _results | map('dict2items')
                      | map('selectattr', 'key', 'in', ['item', 'public_key'])
                      | map('items2dict')
                      | list }}
