---
- tags: [preinstall]
  block:
    - ansible.builtin.include_role:
        name: repository
      vars:
        repos_enabled: [frr]
      when: frr_repo is undefined

    - name: Install Free Range Routing (FRR)
      ansible.builtin.package:
        name: "{{ _common + _specific[ansible_os_family] }}"
      vars:
        _common: [frr, frr-pythontools]
        _specific:
          Debian: []
          RedHat: []
      register: package
      until: package is success
      retries: 12
      delay: 5

    - name: Remove frr.conf (cleanup)
      ansible.builtin.file:
        path: /etc/frr/frr.conf
        state: absent
      register: file_frr_conf

    - name: Configure FRR daemons (cleanup)
      ansible.builtin.replace:
        path: /etc/frr/daemons
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        # NOTE: FRR's staticd uses 2616/TCP port by default, which is the same as FireEdge opens.
        #       To avoid the conflict we change it to 2620.
        - regexp: '^staticd_options="-A 127.0.0.1"'
          replace: 'staticd_options="-A 127.0.0.1 -P 2620"'
      register: replace_daemons

    - name: (Re)Start FRR service (NOW)
      ansible.builtin.service:
        name: frr
        enabled: true
        state: >-
          {{ 'restarted'
              if ((file_frr_conf is changed)
                  or
                  (replace_daemons is changed)) else
             'started' }}
