---
- name: Get Zone 0
  ansible.builtin.shell:
    cmd: onezone show 0 --json
    executable: /bin/bash
  register: shell
  changed_when: false
  ignore_errors: true

- name: Detect or select a Leader
  run_once: true
  ansible.builtin.set_fact:
    # If we cannot detect anything, we default to the first play host.
    leader: >-
      {{ ansible_play_hosts_all[0] if _running is falsy else _leader }}
    # This fact is used to prevent extra/unneeded restart of OpenNebula (triggered via handlers)
    # during initial deployment of a Frontend.
    oned_no_restart: >-
      {{ ansible_play_hosts_all
         if _running is falsy else
         ansible_play_hosts_all | difference(_peer_names) }}
  vars:
    # We process shell results from all Frontends at once.
    _results: >-
      {{ ansible_play_hosts_all | map('extract', hostvars, ['shell']) | list }}
    _running: >-
      {{ _results | selectattr('failed', 'false') | list }}
    _documents: >-
      {{ _running | map(attribute='stdout') | map('from_json') | list }}
    _server_pools: >-
      {{ _documents | map(attribute='ZONE.SERVER_POOL') | select | list }}
    _peers: >-
      {{ [_server_pools[0].SERVER] | flatten | list }}
    _peer_names: >-
      {{ _peers | map(attribute='NAME') | list }}
    _leader: >-
      {{ (_peers | selectattr('STATE', '==', '3') | first).NAME }}

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/join.yml"
  when: inventory_hostname == leader

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/sync.yml"
  when: inventory_hostname != leader

# NOTE: We emulate here `serial: 1` using `loop:` + `delegate_to:` as HA Frontends
# *MUST* be joined strictly sequentially.
- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/join.yml"
    apply:
      delegate_to: "{{ follower }}"
  loop: "{{ _followers }}"
  loop_control: { loop_var: follower }
  vars:
    _followers: >-
      {{ ansible_play_hosts_all | difference([leader]) }}
  when: inventory_hostname == leader

# Wait for the leader to become available (if only a single one is defined).
- ansible.builtin.include_role:
    name: opennebula/leader
  when: ansible_play_hosts_all | count == 1
