---
- name: Get Zone
  ansible.builtin.shell:
    cmd: onezone show '{{ zone_name }}' --json
    executable: /bin/bash
  register: shell
  changed_when: false
  ignore_errors: true

- name: Detect or select a Leader
  ansible.builtin.set_fact:
    # If we cannot detect anything, we default to the first host from the current Federation group.
    leader: >-
      {{ federation.groups.frontend[0] if _running is falsy else _leader }}
    # This fact is used to prevent extra/unneeded restart of OpenNebula (triggered via handlers)
    # during initial deployment of a Front-end.
    oned_no_restart: >-
      {{ federation.groups.frontend
         if _running is falsy else
         federation.groups.frontend | reject('in', _peer_names) }}
  vars:
    # We process shell results from all Front-ends at once.
    _results: >-
      {{ federation.groups.frontend | map('extract', hostvars, ['shell']) | list }}
    _running: >-
      {{ _results | selectattr('failed', 'false') | list }}
    _documents: >-
      {{ _running | map(attribute='stdout') | map('from_json') | list }}
    _server_pools: >-
      {{ _documents | map(attribute='ZONE.SERVER_POOL') | select | list }}
    _peers: >-
      {{ [_server_pools[0].SERVER] | flatten | list }}
    _peer_names: >-
      {{ _peers | map(attribute='NAME') | list }}
    _leader: >-
      {{ (_peers | selectattr('STATE', '==', '3') | first).NAME }}

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/join.yml"
  when: inventory_hostname == leader

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/sync_ha.yml"

# NOTE: We emulate here `serial: 1` using `loop:` + `delegate_to:` as HA Front-ends
#       *MUST* be joined strictly sequentially.
- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/join.yml"
    apply:
      delegate_to: "{{ follower }}"
  loop: "{{ _followers }}"
  loop_control: { loop_var: follower }
  vars:
    _followers: >-
      {{ federation.groups.frontend | reject('in', [leader]) }}
  when: inventory_hostname == leader
