---
- name: Install OpenNebula base packages
  ansible.builtin.package:
    name: "{{ _common + _specific[ansible_os_family] }}"
  vars:
    _common: [opennebula]
    _specific:
      Debian: []
      RedHat: []
  register: package
  until: package is success
  retries: 12
  delay: 5
  tags: [preinstall]

- name: Decide if Frontend should be HA
  ansible.builtin.set_fact:
    use_ha: >-
      {{ (force_ha | bool is true) or (ansible_play_hosts_all | length > 1) }}

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/config.yml"

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/ha.yml"
  when: use_ha is true

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/solo.yml"
  when: use_ha is false

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/admin.yml"
