---
- name: Install OpenNebula base packages
  ansible.builtin.package:
    name: "{{ _common + _specific[ansible_os_family] }}"
  vars:
    _common: [opennebula]
    _specific:
      Debian: []
      RedHat: []
  register: package
  until: package is success
  retries: 12
  delay: 5
  tags: [preinstall]

- name: Decide if Front-end should be HA / Sort-out Federation membership
  ansible.builtin.set_fact:
    use_ha: >-
      {{ (force_ha | bool is true) or (federation.groups.frontend | count > 1) }}

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/config.yml"

- ansible.builtin.include_tasks:
    file: "{{ _tasks[federation.role] }}"
  vars:
    _tasks:
      STANDALONE: "{{ role_path }}/tasks/standalone.yml"
      MASTER: "{{ role_path }}/tasks/master.yml"
      SLAVE: "{{ role_path }}/tasks/slave.yml"

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/admin.yml"
