---
- name: "Handle vfio devices ownership"
  when: pci_passthrough_enabled | bool
  block:
    - name: Create vfio udev rule
      ansible.builtin.copy:
        dest: /etc/udev/rules.d/99-vfio.rules
        content: 'SUBSYSTEM=="vfio", GROUP="kvm", MODE="0666"'
        owner: root
        group: root
        mode: 'u=rw,go=r'

    - name: Reload udev rules
      ansible.builtin.command: udevadm control --reload-rules
      become: true
      register: reload_result
      changed_when: false
      failed_when: reload_result.rc != 0

    - name: Trigger udev events
      ansible.builtin.command: udevadm trigger
      become: true
      register: trigger_result
      changed_when: false
      failed_when: trigger_result.rc != 0

- name: "Manage PCI passthrough devices"
  when: pci_passthrough_enabled | bool
  block:
    - name: "Install driverctl with retries"
      ansible.builtin.package:
        name: driverctl
        state: present
      become: true
      retries: 10
      delay: 5
      register: result
      until: result is succeeded

    - name: "Manage individual PCI devices"
      ansible.builtin.include_tasks: pci_device.yml
      loop: "{{ pci_devices | default([]) }}"
      loop_control:
        loop_var: pci_device
