---
namespace: opennebula
name: deploy
version: 1.0.0

readme: README.md

authors:
- http://opennebula.io <contact@opennebula.io>
description: HA DEPLOYMENT FOR OPENNEBULA (ANSIBLE)

license: []
license_file: LICENSE

tags: [opennebula]

dependencies:
  "ansible.posix": "*"
  "ansible.utils": "*"
  "community.crypto": "*"

repository: https://github.com/OpenNebula/one-deploy
documentation: https://github.com/OpenNebula/one-deploy/wiki
issues: https://github.com/OpenNebula/one-deploy/issues

build_ignore:
- .gitignore
- .env.yml
- inventory
- ansible_collections
