---
- hosts: bastion
  roles:
    - role: bastion
      delegate_to: localhost
      become: false
      tags: [bastion]

- hosts: frontend:node
  strategy: linear
  roles:
    - role: python3

- hosts: frontend:node
  roles:
    - role: facts
      tags: [always]

    - role: precheck
