---
- hosts: frontend
  tags: [frontend]
  roles:
    - role: facts
      tags: [always]

    - role: repository
      tags: [preinstall, prometheus]

    - role: database
    - role: opennebula

    - role: gate
      tags: [gate]

    - role: flow
      tags: [flow]

    - role: gui
      tags: [gui]

- hosts: node
  tags: [node]
  roles:
    - role: facts
      tags: [always]

    - role: repository
      tags: [preinstall, prometheus]

    - role: datastore
      tags: [datastore]

    - role: network
      tags: [network]

    - role: kvm

    - role: prometheus
      tags: [prometheus]
      vars: { node_role: exporter }
      when:
        - ee.prometheus is undefined or ee.prometheus is truthy
        - ee.token is defined and ee.token is truthy

- hosts: frontend
  tags: [frontend]
  roles:
    - role: facts
      tags: [always]

    - role: datastore
      tags: [datastore]

    - role: network
      tags: [network]

    - role: prometheus
      tags: [prometheus]
      vars: { node_role: frontend }
      when:
        - ee.prometheus is undefined or ee.prometheus is truthy
        - ee.token is defined and ee.token is truthy

- hosts: grafana
  roles:
    - role: facts
      tags: [always]

    - role: repository
      tags: [preinstall, grafana]

    - role: grafana
      tags: [grafana]
      when:
        - ee.prometheus is undefined or ee.prometheus is truthy
        - ee.token is defined and ee.token is truthy
