---
- hosts: frontend
  gather_facts: true
  gather_subset: [min]
  tags: [frontend]
  roles:
    - role: repository
      tags: [preinstall]
    - role: database
    - role: opennebula
    - role: datastore
      tags: [datastore]

- hosts: node
  gather_facts: true
  gather_subset: [min]
  tags: [node]
  roles:
    - role: repository
      tags: [preinstall]
    - role: datastore
      tags: [datastore]
    - role: kvm
