---
- hosts: frontend
  gather_facts: true
  gather_subset: [min]
  tags: [frontend]
  roles:
    - role: repository
      tags: [preinstall]

    - role: database
    - role: opennebula

    - role: gate
      tags: [gate]

    - role: flow
      tags: [flow]

    - role: gui
      tags: [gui]

    - role: datastore
      tags: [datastore]

    - role: network
      tags: [network]

- hosts: node
  gather_facts: true
  gather_subset: [min]
  tags: [node]
  roles:
    - role: repository
      tags: [preinstall]

    - role: datastore
      tags: [datastore]

    - role: kvm
