---
- hosts: frontend
  tags: [frontend]
  roles:
    - role: facts
      tags: [always]

    - role: repository
      tags: [preinstall, prometheus]

    - role: database
    - role: opennebula/server

    - role: flush
    - role: opennebula/leader

    - role: gate/server
      tags: [gate]

    - role: flush
    - role: opennebula/leader

    - role: flow
      tags: [flow]

    - role: gui
      tags: [gui]

- hosts: node
  tags: [node]
  roles:
    - role: facts
      tags: [always]

    - role: repository
      tags: [preinstall, prometheus]

    - role: datastore/node
      tags: [datastore]

    - role: network/node
      tags: [network]

    - role: kvm

    - role: gate/proxy
      tags: [gate]
      when:
        - ee.gateproxy is undefined or ee.gateproxy is truthy
        - ee.token is defined and ee.token is truthy

    - role: prometheus/exporter
      tags: [prometheus]
      when:
        - ee.prometheus is undefined or ee.prometheus is truthy
        - ee.token is defined and ee.token is truthy

- hosts: frontend
  tags: [frontend]
  roles:
    - role: facts
      tags: [always]

    - role: datastore/frontend
      tags: [datastore]

    - role: network/frontend
      tags: [network]

    - role: prometheus/server
      tags: [prometheus]
      when:
        - ee.prometheus is undefined or ee.prometheus is truthy
        - ee.token is defined and ee.token is truthy

- hosts: grafana
  roles:
    - role: facts
      tags: [always]

    - role: repository
      tags: [preinstall, grafana]

    - role: prometheus/grafana
      tags: [grafana]
      when:
        - ee.prometheus is undefined or ee.prometheus is truthy
        - ee.token is defined and ee.token is truthy
