---
prerun: false

dependency:
  name: galaxy
  enabled: false

provisioner:
  name: ansible
  playbooks:
    create:  ../resources/playbooks/common/create.yml
    destroy: ../resources/playbooks/common/destroy.yml
  env:
    ANSIBLE_COLLECTIONS_PATHS: ../../
    ANSIBLE_COLLECTIONS_PATH:  ../../
    ANSIBLE_ACTION_PLUGINS:    ../../vendor/ceph-ansible/plugins/actions/
    ANSIBLE_CALLBACK_PLUGINS:  ../../vendor/ceph-ansible/plugins/callback/
    ANSIBLE_FILTER_PLUGINS:    ../../vendor/ceph-ansible/plugins/filter/
    ANSIBLE_ROLES_PATH:        ../../vendor/ceph-ansible/roles/
    ANSIBLE_LIBRARY:           ../../vendor/ceph-ansible/library/
    ANSIBLE_MODULE_UTILS:      ../../vendor/ceph-ansible/module_utils/
  inventory:
    group_vars:
      all:
        env_name: ceph-hci
        ansible_user: root
        ensure_keys_for: [root]
        ensure_hostname: true
        ensure_hosts: true
        update_pkg_cache: true
        one_pass: asd
        one_version: '6.10'
        features: { ceph: true }
        ceph: { repo: community }
        ds: { mode: ceph }
        vn:
          service:
            managed: true
            template:
              VN_MAD: bridge
              BRIDGE: br0
              AR:
                TYPE: IP4
                IP: "{{ '${ONE_RANGE1}'.split()[0] }}"
                SIZE: "{{ '${ONE_RANGE1}'.split()[1] }}"
              NETWORK_ADDRESS: "{{ '${ONE_SUBNET}' | ansible.utils.nthhost(0) }}"
              NETWORK_MASK: "{{ '${ONE_SUBNET}' | ansible.utils.ipaddr('netmask') }}"
              GATEWAY: "{{ '${ONE_SUBNET}' | ansible.utils.nthhost(1) }}"
              DNS: 1.1.1.1 8.8.8.8
        ceph_origin: distro
        public_network: "{{ '${ONE_SUBNET}' }}"
        configure_firewall: false
        no_log_on_ceph_key_tasks: false
        osd_auto_discovery: true
      ceph:
        ceph_stable_release: squid
    host_vars:
      ceph-hci-f1:
        monitor_address: "{{ ansible_host }}"
  config_options:
    defaults:
      gathering: explicit
      host_key_checking: false
      display_skipped_hosts: true
      retry_files_enabled: false
      any_errors_fatal: true
      callbacks_enabled: profile_tasks
      stdout_callback: yaml
    privilege_escalation:
      become: true
      become_user: root
    ssh_connection:
      pipelining: true
  connection_options:
    ansible_ssh_common_args: >-
      -o UserKnownHostsFile=/dev/null
      -o ControlMaster=auto
      -o ControlPersist=60s
      -o ForwardX11=no
      -o LogLevel=ERROR
      -o IdentitiesOnly=no
      -o StrictHostKeyChecking=no

platforms:
  - name: ceph-hci-f1
    groups: [frontend, ceph, mons, mgrs]
    template:
      name: alma9
      content: &content
        CONTEXT:
          GROW_FS: /
          NETCFG_TYPE: networkd
          PASSWORD: asd
        DISK:
          SIZE: 20480
        MEMORY: 4096
        NIC:
          NETWORK: ${ONE_VNET}
    auth: &auth
      host: ${ONE_HOST}
      user: ${ONE_USER}
      pswd: ${ONE_PSWD}

  - name: ceph-hci-n1
    groups: [node, ceph, osds]
    template:
      name: debian12
      content: *content
    datablocks: &datablocks
      - PERSISTENT: "NO"
        DATASTORE_ID: 1
        FORMAT: "qcow2"
        DEV_PREFIX: "vd"
        SIZE: 20480
      - PERSISTENT: "NO"
        DATASTORE_ID: 1
        FORMAT: "qcow2"
        DEV_PREFIX: "vd"
        SIZE: 20480
    auth: *auth

  - name: ceph-hci-n2
    groups: [node, ceph, osds]
    template:
      name: ubuntu2204
      content: *content
    datablocks: *datablocks
    auth: *auth
