---
features_defaults:
  gateproxy: false
  prometheus: false
  passenger: false
  ceph: false

ceph_defaults:
  pool: one
  user: libvirt
  host: >-
    {{ groups[mon_group_name | d('mons')] | map('extract', hostvars, ['ansible_host']) | join(d = ' ')
       if groups[mon_group_name | d('mons')] is defined else
       [] }}
  uuid: null
  repo: distro
