---
features:
  gateproxy: false
  prometheus: false

gate_endpoint: >-
  {{ 'http://169.254.16.9:5030'
     if features.gateproxy | bool is true else
     'http://' ~ one_vip | default(leader) ~ ':5030' }}
