---
features_defaults:
  gateproxy: false
  prometheus: false
  passenger: false
  ceph: false

ceph_defaults:
  pool: one
  user: libvirt
  host: >-
    {{ groups[mon_group_name | d('mons')] | map('extract', hostvars, ['ansible_host']) | join(d = ' ')
       if groups[mon_group_name | d('mons')] is defined else
       [] }}
  uuid: null
  repo: distro

# We define it here, because it's used in both opennebula/* and gate/* roles.
gate_endpoint: >-
  {{ 'http://169.254.16.9:5030'
     if features.gateproxy | bool is true else
     'http://' ~ (one_vip | d(hostvars[leader | d(groups[frontend_group | d('frontend')][0])].ansible_host)) ~ ':5030' }}
