---
- when:
    - pci_devices is sequence
    - pci_devices | count > 0
  block:
    - ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/devices.yml"

    - ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/udev.yml"
