---
- when: pci_passthrough_enabled | bool is true
  block:
    - ansible.builtin.import_tasks:
        file: "{{ role_path }}/tasks/devices.yml"
      when:
        - pci_devices is defined
        - pci_devices is sequence
        - pci_devices | count > 0
