---
- name: Query lspci for devices
  ansible.builtin.shell:
    cmd: |
      set -o errexit -o pipefail
      {% for v in pci_devices_by_vendor_device_class | selectattr('key_type', '==', 'vdc') %}
      STDOUT="$(lspci -vmm -nkD -d '{{ v.key }}')"
      if [[ -n "$STDOUT" ]]; then
        echo "$STDOUT"
        echo
      else
        echo "Could not find '{{ v.key }}'" >&2
        exit 1
      fi
      setpci -v -d '{{ v.key }}' STATUS | while IFS=' ' read -r SLOT _; do
        echo -e "Slot:\t$SLOT"
        if setpci -s "$SLOT" ECAP_SRIOV.B 1>/dev/null; then
          echo -e "Ecap_sriov:\tyes"
        else
          echo -e "Ecap_sriov:\tno"
        fi
        echo -e 'Set_driver:\t{{ v.set_driver | d('vfio-pci') }}'
        echo -e 'Set_name:\t{{ v.set_name | d('omit') }}'
        echo -e 'Set_numvfs:\t{{ v.set_numvfs | d(0) }}'
        echo -e 'Unlisted:\t{{ v.unlisted | d(false) | bool | ternary('yes', 'no') }}'
        echo -e 'Excluded:\t{{ v.excluded | d(false) | bool | ternary('yes', 'no') }}'
        echo
      done
      {% endfor %}
      {% for v in pci_devices_by_address | selectattr('key_type', '==', 'pci') %}
      STDOUT="$(lspci -vmm -nkD -s '{{ v.key }}')"
      if [[ -n "$STDOUT" ]]; then
        echo "$STDOUT"
        echo
      else
        echo "Could not find '{{ v.key }}'" >&2
        exit 1
      fi
      setpci -v -s '{{ v.key }}' STATUS | while IFS=' ' read -r SLOT _; do
        echo -e "Slot:\t$SLOT"
        if setpci -s "$SLOT" ECAP_SRIOV.B 1>/dev/null; then
          echo -e "Ecap_sriov:\tyes"
        else
          echo -e "Ecap_sriov:\tno"
        fi
        echo -e 'Set_driver:\t{{ v.set_driver | d('vfio-pci') }}'
        echo -e 'Set_name:\t{{ v.set_name | d('omit') }}'
        echo -e 'Set_numvfs:\t{{ v.set_numvfs | d(0) }}'
        echo -e 'Unlisted:\t{{ v.unlisted | d(false) | bool | ternary('yes', 'no') }}'
        echo -e 'Excluded:\t{{ v.excluded | d(false) | bool | ternary('yes', 'no') }}'
        echo
      done
      {% endfor %}
      {% for v in pci_devices_by_address | selectattr('key_type', '==', 'mac') %}
      udevadm trigger -nv -s net -a 'address={{ v.key }}' | while read -r DEVPATH; do
        IFS='/' read -r _ SYS DEVICES ROOT _ SLOT _ <<< "$DEVPATH"
        if [[ "$SYS" != sys || "$DEVICES" != devices || "$ROOT" != pci* ]]; then
          continue
        fi
        STDOUT="$(lspci -vmm -nkD -s "$SLOT")"
        if [[ -n "$STDOUT" ]]; then
          echo "$STDOUT"
          echo
        else
          echo "Could not find '$SLOT'" >&2
          exit 1
        fi
        echo -e "Slot:\t$SLOT"
        if setpci -s "$SLOT" ECAP_SRIOV.B 1>/dev/null; then
          echo -e "Ecap_sriov:\tyes"
        else
          echo -e "Ecap_sriov:\tno"
        fi
        if [[ -e "$DEVPATH/address" ]]; then
          echo -e "Address:\t$(cat $DEVPATH/address)"
        fi
        echo -e 'Set_driver:\t{{ v.set_driver | d('vfio-pci') }}'
        echo -e 'Set_name:\t{{ v.set_name | d('omit') }}'
        echo -e 'Set_numvfs:\t{{ v.set_numvfs | d(0) }}'
        echo -e 'Unlisted:\t{{ v.unlisted | d(false) | bool | ternary('yes', 'no') }}'
        echo -e 'Excluded:\t{{ v.excluded | d(false) | bool | ternary('yes', 'no') }}'
        echo
      done
      {% endfor %}
    executable: /bin/bash
  register: shell_lspci
  changed_when: false

- name: Parse lspci's output
  ansible.builtin.set_fact:
    lspci_devices: >-
      {{ _lspci_devices | rejectattr('Excluded', '==', 'yes') }}
  vars:
    _lspci_devices: >-
      {%- set output = {} -%}
      {%- for v in _lspci_devices_raw -%}
        {{- output.update(output | combine({v.Slot: v}, recursive=true)) -}}
      {%- endfor -%}
      {{- output.values() | list -}}
    _lspci_devices_raw: >-
      {{ shell_lspci.stdout | split(_sep1)
                            | select('truthy')
                            | map('split', _sep2)
                            | map('map', 'split', _sep3)
                            | map('items2dict', key_name=0, value_name=1) }}
    _sep1: "\n\n"
    _sep2: "\n"
    _sep3: ":\t" # noqa no-tabs

- when:
    - pci_forbidden_addresses is undefined
    - _default is defined
    - _interfaces | count > 0
  vars:
    _facts: >-
      {{ ansible_facts }}
    _default: >-
      {{ _facts.default_ipv4.interface }}
    # NOTE: It also handles nested bridge/bond interfaces..
    _interfaces: >-
      {%- set output = [] -%}
      {%- for v in _facts[_default].interfaces | d(_facts[_default].slaves) | d([_facts[_default].device | d(none)] | select) -%}
        {{- output.append(_facts[v].slaves | d([_facts[v].device | d(none)] | select)) -}}
      {%- endfor -%}
      {{- output | flatten -}}
    # Do also a quick crosscheck with OVS/DPDK config (when available).
    _dpdk_pci_addrs: >-
      {{ (ovs.iface | d({})).values() | map(attribute='set', default=[])
                                      | map('selectattr', 'options:dpdk-devargs', 'defined')
                                      | select
                                      | flatten
                                      | map(attribute='options:dpdk-devargs') }}
    _dpdk_interfaces: >-
      {{ (ovs.iface | d({})).keys() | intersect(_facts.interfaces) }}
  block:
    - name: Query udev for device info
      ansible.builtin.command:
        cmd: "udevadm info --query=property --property=ID_PATH --value {{ _paths | join(' ') }}"
      vars:
        _paths: >-
          {{ (_interfaces + _dpdk_interfaces) | unique
                                              | map('regex_replace', '^(.*)$', "-p '/sys/class/net/\g<1>'") }}
      register: command_udevadm_info
      changed_when: false

    - name: Gather forbidden PCI addresses
      ansible.builtin.set_fact:
        pci_forbidden_addresses: "{{ (_pci_addrs + _dpdk_pci_addrs) | unique }}"
      vars:
        _pci_addrs: >-
          {{ command_udevadm_info.stdout_lines | select
                                               | map('regex_replace', '^pci-', '') }}

- name: Assert 'lspci_devices' contains no forbidden PCI addresses
  ansible.builtin.assert:
    that: (pci_forbidden_addresses is undefined)
          or
          (pci_forbidden_addresses | count == 0)
          or
          (_detected | count == 0)
    fail_msg: >-
      Forbidden PCI addresses {{ _detected }} detected, aborting!
      Please adjust 'pci_devices' to exclude forbidden PCI addresses.
      You might also want to look for conflicts with OVS/DPDK config.
  vars:
    _detected: >-
      {{ lspci_devices | map(attribute='Slot') | intersect(pci_forbidden_addresses) }}
