---
- when: lspci_devices | count > 0
  vars:
    # NOTE: This marks items with indices that can be later used to rename devices.
    _lspci_devices: >-
      {%- set ns = namespace(output=[], i=0) -%}
      {%- for v in lspci_devices -%}
        {%- if v.Set_counter is defined -%}
          {%- set ns.i = v.Set_counter | int -%}
        {%- endif -%}
        {%- set ns.output = ns.output + [v | combine({"Index": ns.i})] -%}
        {%- set ns.i = ns.i + 1 -%}
      {%- endfor -%}
      {{- ns.output -}}

    _sriov_devices: >-
      {{ _lspci_devices | selectattr('Ecap_sriov', '==', 'yes') }}

    _all: >-
      {{ _lspci_devices | selectattr('Class', 'defined')
                        | selectattr('Driver', 'defined')
                        | selectattr('Slot', 'defined') }}

    _to_unmanage: >-
      {{ _all | selectattr('Class', 'in', ['0200'])
              | rejectattr('Driver', 'in', ['vfio-pci']) }}

    _to_rename: >-
      {{ _all | selectattr('Set_name', 'defined')
              | rejectattr('Set_name', '==', 'omit') }}

    _to_rename_net: >-
      {{ _to_rename | selectattr('Class', 'in', ['0200'])
                    | rejectattr('Driver', 'in', ['vfio-pci']) }}

    _to_rename_vfio: >-
      {{ _to_rename | selectattr('IOMMUGroup', 'defined') }}

    _vf_to_pf: >-
      {{ shell_pf_vf_fn.stdout_lines | d([])
                                     | map('split', ';')
                                     | items2dict(key_name=1, value_name=0) }}

    _vf_to_fn: >-
      {{ shell_pf_vf_fn.stdout_lines | d([])
                                     | map('split', ';')
                                     | items2dict(key_name=1, value_name=2) }}

    _names: >-
      {%- set output = {} -%}
      {# Resolve basic 0-3 args. #}
      {%- for v in _to_rename -%}
        {{-
          output.update({
            v.Slot: [
              v.Slot | regex_findall('[0-9a-fA-F]+'),
              _vf_to_pf.get(v.Slot, '') | regex_findall('[0-9a-fA-F]+'),
              _vf_to_fn.get(v.Slot, ''),
              v.Index | d(0),
            ],
          })
        -}}
      {%- endfor -%}
      {# Add 4th arg (PF's name). #}
      {%- for v in _to_rename | selectattr('Slot', 'in', _vf_to_pf) -%}
        {%- set p = _lspci_devices | selectattr('Slot', '==', _vf_to_pf[v.Slot]) | first -%}
        {%- if p.Set_name != 'omit' -%}
          {{-
            output.update({
              v.Slot: output[v.Slot] + [p.Set_name.format(*output[p.Slot])],
            })
          -}}
        {%- endif -%}
      {%- endfor -%}
      {# Construct all names from templates and args. #}
      {%- for v in _to_rename -%}
        {{-
          output.update({
            v.Slot: v.Set_name.format(*output[v.Slot]),
          })
        -}}
      {%- endfor -%}
      {{- output -}}
  block:
    - name: Scan /sys/bus/pci/devices/*/virtfn* (SR-IOV)
      ansible.builtin.shell:
        cmd: |
          set -o errexit -o pipefail; shopt -s nullglob
          {% for v in _sriov_devices %}
          for VF_PATH in '/sys/bus/pci/devices/{{ v.Slot }}/virtfn'*; do
            VF="$(basename "$(realpath "$VF_PATH")")"
            FN="$(basename "$VF_PATH")"
            echo "{{ v.Slot }};$VF;${FN#virtfn}"
          done
          {% endfor %}
        executable: /bin/bash
      register: shell_pf_vf_fn
      changed_when: false
      when: _sriov_devices | count > 0

    - name: Render extra udev rules (/etc/udev/rules.d)
      ansible.builtin.copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content }}"
        owner: 0
        group: 0
        mode: u=rw,go=r
      loop_control: { label: "{{ item.dest }}" }
      loop:
        - dest: /etc/udev/rules.d/99-mode.rules
          content: |
            # managed by one-deploy
            SUBSYSTEM=="vfio", ACTION=="add", GROUP="kvm", MODE="0666"
        - dest: /etc/udev/rules.d/99-rename.rules
          content: |
            # managed by one-deploy
            # --- NET
            {% for v in _to_rename_net %}
            # {{ v.Slot }} <- {{ _names[v.Slot] }}
            SUBSYSTEM=="net", ACTION=="add", ENV{ID_PATH}=="pci-{{ v.Slot }}", NAME="{{ _names[v.Slot] }}"
            {% endfor %}
            # --- VFIO
            {% for v in _to_rename_vfio %}
            # {{ v.Slot }} <- {{ _names[v.Slot] }}
            SUBSYSTEM=="vfio", ACTION=="add", SYMLINK+="vfio/by-tag/{{ _names[v.Slot] }}", \
            PROGRAM="/usr/bin/test /sys/bus/pci/devices/{{ v.Slot }}/iommu_group -ef /sys/kernel/iommu_groups/%k"
            {% endfor %}
        # NOTE: NM_UNMANAGED does not seem to be sufficient (unless you reboot) as NM ignores settings in UDEV in case
        #       the device is already managed.
        #       FORCE_NM_UNMANAGED that is non-standard variable, used here as NM_UNMANAGED can be modifed by
        #       something else.
        #       "/usr/bin/systemd-run --no-block" is used here to never block UDEV + existence of the device can be verified
        #       without spawning extra shell.
        - dest: /etc/udev/rules.d/99-unmanage.rules
          content: |
            # managed by one-deploy
            # --- NET
            {% for v in _to_unmanage %}
            # {{ v.Slot }}
            SUBSYSTEM=="net", ACTION=="add|move", ENV{ID_PATH}=="pci-{{ v.Slot }}", \
            ENV{NM_UNMANAGED}="1", ENV{FORCE_NM_UNMANAGED}="1"
            SUBSYSTEM=="net", ENV{ID_PATH}=="pci-{{ v.Slot }}", ENV{FORCE_NM_UNMANAGED}=="1", TEST=="/usr/bin/nmcli", \
            RUN+="/usr/bin/systemd-run --no-block --property=ConditionPathExists=/sys%E{DEVPATH} \
                  /usr/bin/nmcli device set %E{ID_NET_NAME} managed no"
            SUBSYSTEM=="net", ENV{ID_PATH}=="pci-{{ v.Slot }}", ENV{FORCE_NM_UNMANAGED}=="1", TEST=="/usr/sbin/netplan", \
            RUN+="/usr/bin/systemd-run --no-block --property=ConditionPathExists=/sys%E{DEVPATH} \
                  /usr/sbin/netplan set network.ethernets.%E{ID_NET_NAME_PATH}=null"
            SUBSYSTEM=="net", ACTION=="add|move", ENV{ID_PATH}=="pci-{{ v.Slot }}", TEST=="/usr/sbin/ip", \
            RUN+="/usr/bin/systemd-run --no-block --property=ConditionPathExists=/sys%E{DEVPATH} \
                  /usr/sbin/ip link set dev %E{INTERFACE} up"
            {% endfor %}
      register: copy_udev_rules

    - name: Refresh udev rules
      ansible.builtin.shell:
        cmd: udevadm control --reload-rules && udevadm trigger --action=add
      changed_when: true
      when: copy_udev_rules is changed
