---
all:
  vars:
    env_name: example
    ansible_user: example
    ensure_keys_for: [example, root]
    one_version: '6.8'
    one_token: example:example
    features:
      gateproxy: true
      prometheus: false
    one_vip: 10.11.12.69
    one_vip_cidr: 24
    one_vip_if: eth0
    vn:
      service:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eth0
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: 10.11.12.200
            SIZE: 48
          NETWORK_ADDRESS: 10.11.12.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 10.11.12.1
          DNS: 1.1.1.1
      vm:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eth1
          AR:
            TYPE: IP4
            IP: 192.168.150.200
            SIZE: 48
          NETWORK_ADDRESS: 192.168.150.0
          NETWORK_MASK: 255.255.255.0
    ds:
      mode: ssh
      config:
        mounts:
          - type: image
            path: /opt/nfs0/1/
          - type: file
            path: /opt/nfs0/2/

bastion:
  hosts:
    b1: { ansible_host: 10.11.12.10 }

frontend:
  hosts:
    f1: { ansible_host: 10.11.12.10 }
    f2: { ansible_host: 10.11.12.20 }
    f3: { ansible_host: 10.11.12.30 }

node:
  hosts:
    n1: { ansible_host: 10.11.12.40 }
    n2: { ansible_host: 10.11.12.50 }

grafana:
  hosts:
    f1: { ansible_host: 10.11.12.10 }
