---
all:
  vars:
    ansible_user: root
    one_version: '6.8'
    one_pass: opennebulapass
    ds:
      mode: shared
      config:
        mounts:
        - type: system
          path: /mnt/0
        - type: image
          path: /mnt/1
        - type: file
          path: /mnt/2
    vn:
      admin_net:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eth0
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: 172.20.0.100
            SIZE: 48
          NETWORK_ADDRESS: 172.20.0.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 172.20.0.1
          DNS: 1.1.1.1

frontend:
  hosts:
    f1: { ansible_host: 172.20.0.6 }

node:
  hosts:
    n1: { ansible_host: 172.20.0.7 }
    n2: { ansible_host: 172.20.0.8 }
