---
all:
  vars:
    env_name: shared
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: example
    ensure_keys_for: [example, root]
    one_version: '6.6'
    one_token: example:example
    one_vip: 10.11.12.69
    one_vip_cidr: 24
    one_vip_if: eth0
    ds:
      mode: shared
      config:
        mounts:
          - type: system
            path: /opt/nfs0/0/
          - type: image
            path: /opt/nfs0/1/
          - type: file
            path: /opt/nfs0/2/

bastion:
  hosts:
    b1: { ansible_host: 10.11.12.10 }

frontend:
  hosts:
    f1: { ansible_host: 10.11.12.10 }
    f2: { ansible_host: 10.11.12.20 }
    f3: { ansible_host: 10.11.12.30 }

node:
  hosts:
    n1: { ansible_host: 10.11.12.40 }
    n2: { ansible_host: 10.11.12.50 }

grafana:
  hosts:
    f1: { ansible_host: 10.11.12.10 }
