---
all:
  vars:
    env_name: shared
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: example
    ensure_keys_for: [example, root]
    one_version: '6.8'
    one_token: example:example
    one_vip: 10.11.12.69
    one_vip_cidr: 24
    one_vip_if: eth0
    ds:
      mode: generic
      config:
        SYSTEM_DS:
          system:
            enabled: false
          system1:
            id: 100
            managed: true
            enabled: true
            symlink:
              groups: [node]
              src: /opt/nfs1/100/
            template: &template
              TYPE: SYSTEM_DS
              TM_MAD: shared
              BRIDGE_LIST: "{{ groups.node | map('extract', hostvars, ['ansible_host']) | join(' ') }}"
          system2:
            id: 101
            managed: true
            enabled: true
            symlink:
              groups: [node]
              src: /opt/nfs2/101/
            template: *template
          system3:
            id: 102
            managed: true
            enabled: true
            symlink:
              groups: [node]
              src: /opt/nfs3/102/
            template: *template
        IMAGE_DS:
          default:
            symlink: { src: /opt/nfs0/1/ }
            template:
              TM_MAD: shared
        FILE_DS:
          files:
            symlink: { src: /opt/nfs0/2/ }

bastion:
  hosts:
    b1: { ansible_host: 10.11.12.10 }

frontend:
  hosts:
    f1: { ansible_host: 10.11.12.10 }
    f2: { ansible_host: 10.11.12.20 }
    f3: { ansible_host: 10.11.12.30 }

node:
  hosts:
    n1: { ansible_host: 10.11.12.40 }
    n2: { ansible_host: 10.11.12.50 }

grafana:
  hosts:
    f1: { ansible_host: 10.11.12.10 }
