---
- tags: [preinstall]
  block:
    - ansible.builtin.include_role:
        name: repository
      vars:
        repos_enabled_defaults: [opennebula]
      when: opennebula_repo is undefined

    - name: Install Prometheus with dependencies
      ansible.builtin.package:
        name: "{{ _common + _specific[ansible_os_family] }}"
      vars:
        _common:
          - bash
          - opennebula-prometheus-{{ node_hypervisor }}
        _specific:
          Debian: []
          RedHat: []
      register: package
      until: package is success
      retries: 12
      delay: 5

- vars:
    _loop:
      - name: opennebula-libvirt-exporter.service
        dest: /etc/systemd/system/opennebula-libvirt-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-libvirt-exporter.service.jinja"
      - name: opennebula-node-exporter.service
        dest: /etc/systemd/system/opennebula-node-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-node-exporter.service.jinja"
  block:
    - name: Override systemd units (mkdir)
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: 0
        group: 0
        mode: u=rwx,go=rx
      loop: "{{ _loop }}"

    - name: Override systemd units
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
        owner: 0
        group: 0
        mode: u=rw,go=r
      loop: "{{ _loop }}"
      register: template_override_units

    - name: Enable / Start / Restart Prometheus exporters (NOW)
      ansible.builtin.systemd_service:
        name: "{{ item.name }}"
        enabled: true
        state: >-
          {{ 'restarted' if _changed else 'started' }}
        daemon_reload: >-
          {{ _changed }}
      loop: "{{ _loop }}"
      vars:
        _changed: >-
          {{ template_override_units is changed }}
