---
- tags: [preinstall]
  block:
    - ansible.builtin.include_role:
        name: repository
      vars:
        repos_enabled: [opennebula]
      when: opennebula_repo is undefined

    - name: Install FireEdge and dependencies
      ansible.builtin.package:
        name: "{{ _common + _specific[ansible_os_family] }}"
      vars:
        _common: [opennebula-fireedge]
        _specific:
          Debian: []
          RedHat: []
      register: package
      until: package is success
      retries: 12
      delay: 5

- ansible.builtin.include_role:
    name: opennebula/leader
  when: leader is undefined

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/config.yml"

- name: Enable FireEdge Server (NOW)
  ansible.builtin.service:
    name: opennebula-fireedge
    enabled: true

- name: Start FireEdge Server (NOW)
  ansible.builtin.service:
    name: opennebula-fireedge
    state: started
  register: service_fireedge

- name: Install Web Server
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/{{ ssl.web_server }}.yml"

- name: Ensure FireEdge and Sunstone are not restarted twice
  ansible.builtin.set_fact:
    gui_no_restart: >-
      {{ service_fireedge is changed }}
