---
- name: Install FireEdge, Sunstone and dependencies
  ansible.builtin.package:
    name: "{{ _common + _specific[ansible_os_family] }}"
  vars:
    _common: [opennebula-fireedge, opennebula-sunstone]
    _specific:
      Debian: []
      RedHat: []
  register: package
  until: package is success
  retries: 12
  delay: 5
  tags: [preinstall]

- ansible.builtin.include_role:
    name: opennebula/leader
  when: leader is undefined

- ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/config.yml"

- name: Enable FireEdge Server (NOW)
  ansible.builtin.service:
    name: opennebula-fireedge
    enabled: true

- name: Start FireEdge Server (NOW)
  ansible.builtin.service:
    name: opennebula-fireedge
    state: started
  register: service_fireedge

- when: features.passenger | bool is false
  block:
    - name: Enable Sunstone Server (NOW)
      ansible.builtin.service:
        name: opennebula-sunstone
        enabled: true

    - name: Start Sunstone Server (NOW)
      ansible.builtin.service:
        name: opennebula-sunstone
        state: started
      register: service_sunstone

- when: features.passenger | bool is true
  block:
    - name: Disable / Stop Sunstone Server (NOW)
      ansible.builtin.service:
        name: opennebula-sunstone
        enabled: false
        state: stopped

    - ansible.builtin.import_tasks:
        file: "{{ role_path }}/tasks/passenger.yml"

- name: Ensure FireEdge and Sunstone are not restarted twice
  ansible.builtin.set_fact:
    gui_no_restart: >-
      {{ service_fireedge is changed and service_sunstone is changed }}
