---
- when: _input | count > 0
  vars:
    _input: >-
      {{ sunstone_views | d([]) }}
    _values_loaded: >-
      {{ cfgtool_groups_and_views['values'] }}
    _groups_loaded: >-
      {{ _values_loaded.0.0 }}
    _views_loaded: >-
      {{ _values_loaded.1.0 }}
    _groups_updated: >-
      {%- set output = _groups_loaded -%}
      {%- for v in _input -%}
        {%- for g in v.groups -%}
          {{-
            output.update({ g: (output[g] | d([]) + [v.name]) | unique })
          -}}
        {%- endfor -%}
      {%- endfor -%}
      {{- output -}}
    _views_updated: >-
      {%- set output = _views_loaded -%}
      {%- for v in _input -%}
        {{-
          output.update({ v.name: { "name": v.label, "description": v.description } })
        -}}
      {%- endfor -%}
      {{- output -}}
  block:
    - name: Copy custom Sunstone views from inventory
      ansible.builtin.copy:
        dest: "{{ _dest | normpath }}/" # / is strictly required here
        src: "{{ _src | normpath }}/"   # / is strictly required here
        mode: u=rw,go=r
      vars:
        _dest: >-
          {{ sunstone_views_base_dir }}/{{ item.name }}
        _src: >-
          {{ inventory_dir }}/views/{{ item.source_folder }}
      loop: "{{ _input }}"
      loop_control: { label: "{{ item.name }}" }

    - name: Read 'groups' and 'views' from sunstone-views.yaml
      opennebula.deploy.cfgtool:
        dest: "{{ sunstone_views_config_file }}"
        parser: Yaml
        actions:
          - get:
              path: [groups]
          - get:
              path: [views]
      register: cfgtool_groups_and_views

    - name: Write updated 'groups' and 'views' into sunstone-views.yaml
      opennebula.deploy.cfgtool:
        dest: "{{ sunstone_views_config_file }}"
        parser: Yaml
        actions:
          - put:
              path: [groups]
              value: "{{ _groups_updated }}"
          - put:
              path: [views]
              value: "{{ _views_updated }}"
