---
- name: Configure Alertmanager
  ansible.builtin.copy:
    dest: /etc/one/alertmanager/alertmanager.yml
    owner: 0
    group: 0
    mode: u=rw,go=r
    content: "{{ alertmanager_config }}"
  register: copy_alertmanager_yml

- vars:
    _peers: >-
      {{ ansible_play_hosts_all | reject('in', [inventory_hostname])
                                | map('regex_replace', '^(.*)$', ' --cluster.peer=\g<1>:9094 ')
                                | join }}
    _loop:
      - name: opennebula-alertmanager.service
        dest: /etc/systemd/system/opennebula-alertmanager.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-alertmanager.service.jinja"
  block:
    - name: Override systemd units (mkdir)
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: 0
        group: 0
        mode: u=rwx,go=rx
      loop: "{{ _loop }}"

    - name: Override systemd units
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
        owner: 0
        group: 0
        mode: u=rw,go=r
      loop: "{{ _loop }}"
      register: template_override_units

    - name: Enable / Start / Restart Alertmanager service (NOW)
      ansible.builtin.systemd_service:
        name: "{{ item.name }}"
        enabled: true
        state: >-
          {{ 'restarted' if _changed else 'started' }}
        daemon_reload: >-
          {{ _changed }}
      loop: "{{ _loop }}"
      vars:
        _changed: >-
          {{ copy_alertmanager_yml is changed or template_override_units is changed }}
