---
- ansible.builtin.import_role:
    name: prometheus/common

- name: Install Prometheus and dependencies
  ansible.builtin.package:
    name: "{{ _common + _specific[ansible_os_family] }}"
  vars:
    _common:
      - bash
      - opennebula-prometheus
      - opennebula-prometheus-{{ node_hypervisor }}
    _specific:
      Debian: []
      RedHat: []
  tags: [preinstall]

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/prometheus.yml"
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/alertmanager.yml"
