---
- name: Patch Prometheus datasources
  ansible.builtin.shell:
    cmd: |
      set -o errexit
      BEFORE=$(cksum /etc/one/prometheus/prometheus.yml)
      /usr/share/one/prometheus/patch_datasources.rb
      AFTER=$(cksum /etc/one/prometheus/prometheus.yml)
      if [[ "$AFTER" == "$BEFORE" ]]; then
        exit 0
      else
        exit 78 # EREMCHG
      fi
    executable: /bin/bash
  register: shell_patch_datasources
  changed_when:
    - shell_patch_datasources.rc in [78]
  failed_when:
    - shell_patch_datasources.rc not in [0, 78]

- vars:
    _loop:
      - when: "{{ true }}"
        name: opennebula-exporter.service
        pkg: "opennebula-prometheus-{{ node_hypervisor }}"
        dest: /etc/systemd/system/opennebula-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-exporter.service.jinja"

      - when: "{{ one_version is version('7.2.1', '>=') }}"
        name: opennebula-mysql-exporter.service
        pkg: opennebula-prometheus-mysql
        dest: /etc/systemd/system/opennebula-mysql-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-mysql-exporter.service.jinja"

      - when: "{{ true }}"
        name: opennebula-node-exporter.service
        pkg: "opennebula-prometheus-{{ node_hypervisor }}"
        dest: /etc/systemd/system/opennebula-node-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-node-exporter.service.jinja"

      - when: "{{ one_version is version('7.2.1', '>=') and (ovs_enabled | d(false)) }}"
        name: opennebula-ovs-exporter.service
        pkg: opennebula-prometheus-ovs
        dest: /etc/systemd/system/opennebula-ovs-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-ovs-exporter.service.jinja"

      - when: "{{ true }}"
        name: opennebula-prometheus.service
        pkg: null # already installed
        dest: /etc/systemd/system/opennebula-prometheus.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-prometheus.service.jinja"

      - when: "{{ one_version is version('7.2.1', '>=') }}"
        name: opennebula-smartctl-exporter.service
        pkg: opennebula-prometheus-smartctl
        dest: /etc/systemd/system/opennebula-smartctl-exporter.service.d/override.conf
        src: "{{ role_path }}/../common/templates/opennebula-smartctl-exporter.service.jinja"
  block:
    - name: Install Prometheus exporters
      ansible.builtin.package:
        name: "{{ _common + _pkgs }}"
      vars:
        _common: [bash]
        _pkgs: >-
          {{ _loop | selectattr('when') | map(attribute='pkg') | select | unique }}
      register: package
      until: package is success
      retries: 12
      delay: 5

    - name: Override systemd units (mkdir)
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: 0
        group: 0
        mode: u=rwx,go=rx
      when: item.when
      loop: "{{ _loop }}"

    - name: Override systemd units
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
        owner: 0
        group: 0
        mode: u=rw,go=r
      when: item.when
      loop: "{{ _loop }}"
      register: template_override_units

    - name: Enable / Start / Restart Prometheus service and exporters (NOW)
      ansible.builtin.systemd_service:
        name: "{{ item.name }}"
        enabled: true
        state: >-
          {{ 'restarted' if _changed else 'started' }}
        daemon_reload: >-
          {{ _changed }}
      when: item.when
      loop: "{{ _loop }}"
      vars:
        _changed: >-
          {{ shell_patch_datasources is changed or template_override_units is changed }}
