---
alertmanager_config: |
  ---
  global:
    resolve_timeout: 5m

  route:
    group_by: [alertname]
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 1h
    receiver: discard

  receivers:
    - name: discard

  templates: []

  inhibit_rules:
    - source_match:
        severity: critical
      target_match:
        severity: warning
      equal: [alertname, dev, instance]
