---
- name: Guess the Leader
  ansible.builtin.set_fact:
    leader: >-
      {{ one_vip | default(groups.frontend | random)
         if groups.frontend | length > 1 else
         groups.frontend[0] }}
  run_once: true

- delegate_to: "{{ leader }}"
  run_once: true
  block:
    - name: Decrement the retry counter
      ansible.builtin.set_fact:
        retry_no: >-
          {{ retry_no | default(6, true) | int - 1 }}

    - name: Get Zone 0
      ansible.builtin.shell:
        cmd: onezone show 0 --json
        executable: /bin/bash
      register: shell
      changed_when: false

    - name: Detect if the Leader is there
      ansible.builtin.fail:
      when: _server_pool is truthy and _leader is falsy
      vars:
        _document: >-
          {{ shell.stdout | from_json }}
        _server_pool: >-
          {{ _document.ZONE.SERVER_POOL }}
        _peers: >-
          {{ [_server_pool.SERVER] | flatten | list }}
        _leader: >-
          {{ _peers | selectattr('STATE', '==', '3') | list }}
  rescue:
    - name: Abort after timeout
      ansible.builtin.fail:
      when: retry_no | int == 0

    - name: Pause for 10 seconds
      ansible.builtin.pause:
        seconds: 10

    - name: Continue the retry loop
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/leader.yml"
