---
- name: Install OpenNebula base packages
  ansible.builtin.package:
    name: "{{ _name[ansible_os_family] }}"
  vars:
    _name:
      Debian: [opennebula]
      RedHat: [opennebula]
  tags: [preinstall]

- name: Decide if Frontend should be HA
  ansible.builtin.set_fact:
    use_ha: >-
      {{ force_ha is truthy or groups.frontend | length > 1 }}

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/config.yml"

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/ha.yml"
  when: use_ha is true

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/solo.yml"
  when: use_ha is false

- name: Flush handlers
  meta: flush_handlers
