---
private_fireedge_endpoint: http://localhost:2616

ssl_defaults:
  web_server: apache # could be nginx
  key: /etc/ssl/private/opennebula-key.pem
  certchain: /etc/ssl/certs/opennebula-certchain.pem

sunstone_views: []
sunstone_views_config_file: /etc/one/fireedge/sunstone/views/sunstone-views.yaml
sunstone_views_base_dir: /etc/one/fireedge/sunstone/views/
