---
private_fireedge_endpoint: http://localhost:2616

ssl_defaults:
  web_server: apache # could be nginx
  key: /etc/ssl/private/opennebula-key.pem
  certchain: /etc/ssl/certs/opennebula-certchain.pem
