---
- name: Provision Datastores (frontend)
  ansible.builtin.include_role:
    name: "datastore/{{ _mode_to_role[ds.mode] }}"
  vars:
    _target_group: >-
      {{ frontend_group | d('frontend') }}
    _mode_to_role:
      ssh: simple
      qcow2: simple
      shared: simple
      generic: generic
  when:
    - ds.mode is defined
