---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  collections:
    - opennebula.deploy
  tasks:
    - name: Destroy instances
      opennebula.deploy.named_vm:
        name: "{{ item.name }}"
        state: absent
        auth: "{{ item.auth }}"
      loop: "{{ molecule_yml.platforms }}"
      register: server

    - name: Dump instance config
      ansible.builtin.copy:
        dest: "{{ molecule_instance_config }}"
        mode: u=rw,go=
        content: |
          {{ _instance_conf | to_yaml }}
      vars:
        _instance_conf: {}
      when: server is changed
