---
- name: Wait until all hosts are reachable again. Important in HCI deployments, where the host where FEs are has just been rebooted
  wait_for_connection:
    timeout: 300
    delay: 10
    sleep: 5

- name: Modify PCI monitoring probe. Case with empty list
  ansible.builtin.replace:
    path: /var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf
    regexp: "^:filter:\\s*'0:0'"
    replace: |
      :filter:
        - '10de:*'

- name: Modify PCI monitoring probe. Casy with already populated list
  ansible.builtin.lineinfile:
    path: /var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf
    line: "  - '10de:*'"
    insertafter: '^:filter:'
    state: present
    create: false

- name: Identify the current active frontend
  ansible.builtin.include_role:
    name: opennebula/leader
  when: leader is undefined

- name: Update drivers in the rest of the nodes
  when: inventory_hostname == leader
  become_user: oneadmin
  ansible.builtin.command: onehost sync --force
  changed_when: false
