---
- name: Get information about the NVIDIA GPUs of each host
  ansible.builtin.script: "{{ role_path }}/scripts/nvidia_gpus.sh"
  register: passthrough_nvidia_devices
  changed_when: false

# TODO: Verify first if each task is needed
- name: Tasks will only apply to hosts with at least 1 NVIDIA GPU
  when: passthrough_nvidia_devices.stdout | from_json | length > 0
  block:
    - name: Load vfio kernel modules
      ansible.builtin.copy:
        dest: "/etc/modules-load.d/60-vfio-pci.conf"
        owner: root
        group: root
        mode: '0644'
        content: |
          vfio
          vfio_iommu_type1
          vfio_pci
      notify:
        - Update Initramfs
        - Reboot Machine

    - name: Blacklist nouveau and nvidia drivers
      ansible.builtin.copy:
        dest: "/etc/modprobe.d/60-blacklist-nouveau-nvidia.conf"
        owner: root
        group: root
        mode: '0644'
        content: |
          blacklist nouveau
          blacklist nvidia
          options nouveau modeset=0
          options nvidia modeset=0
      notify:
        - Update Initramfs
        - Reboot Machine

    - name: Assign vfio-pci driver to NVIDIA GPUs and the devices in the their IOMMU group
      ansible.builtin.copy:
        dest: "/etc/modprobe.d/70-vfio-devices.conf"
        owner: root
        group: root
        mode: '0644'
        content: "options vfio-pci ids={{ _vendor_device_ids }}"
      notify:
        - Update Initramfs
        - Reboot Machine
      vars:
        _vendor_device_ids: >-
          {{
            passthrough_nvidia_devices.stdout
            | from_json
            | map(attribute='iommu_group_devices')
            | map('map', attribute='vendor_device_id')
            | flatten
            | unique
            | join(',')
          }}

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
