---
# We only support active Ceph releases (https://docs.ceph.com/en/latest/releases/index.html)
- name: Check if specified Ceph release is supported
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          ((ceph.release is defined) and (ceph.release in _supported))
    fail_msg: Please specify one of the supported Ceph versions {{ _supported }} in ceph.release variable.
  vars:
    _supported:
      - squid
      - tentacle
  tags: [preinstall]

# We only support active Ceph releases (https://docs.ceph.com/en/latest/releases/index.html)
# and recommended distro families (https://docs.ceph.com/en/latest/start/os-recommendations/)
# Other useful links:
# - https://sigs.centos.org/storage/general/
# - https://ubuntu.com/ceph/docs/supported-ceph-versions
- name: Check if Ceph feature is supported for current distro family
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          ((ceph.release is defined) and (_repo in _repos))
    fail_msg: Please use one of the supported linux distro families to run Ceph {{ ceph.release | d('') }} version
              ({{ ansible_distribution }}/{{ ansible_distribution_major_version }}/{{ _repo }} combination is unsupported).
  vars:
    _repo: "{{ ceph.repo | d('community') }}"
    _repos: "{{ _supported[ceph.release][ansible_distribution][ansible_distribution_major_version] }}"
    _supported:
      squid: # Ceph 19.2.z
        Debian:
          '12': [community]
          '13': []
        Ubuntu:
          '22': [community]
          '24': [distro]
        AlmaLinux:
          '9': [community]
          '10': []
        RedHat:
          '9': [community]
          '10': []
        openSUSE Leap:
          '16': []
      tentacle: # Ceph 20.2.z
        Debian:
          '12': [community]
          '13': []
        Ubuntu:
          '22': [community]
          '24': [community]
          '26': [distro]
        AlmaLinux:
          '9': [community]
          '10': [community]
        RedHat:
          '9': [community]
          '10': [community]
        openSUSE Leap:
          '16': []
  tags: [preinstall]

- name: Assert that ansible_host is always an IP address in Ceph inventory groups
  ansible.builtin.assert:
    that: _addresses is all
    fail_msg: Currently ansible_host must be an IP address for every Ceph cluster member.
              Please adjust your inventory.
  vars:
    _groups:
      - "{{ mon_group | d('mon') }}"
      - "{{ mgr_group | d('mgr') }}"
      - "{{ osd_group | d('osd') }}"
    _addresses: >-
      {{ _groups | map('extract', groups)
                 | select('defined')
                 | flatten
                 | select
                 | map('extract', hostvars)
                 | select('defined')
                 | map(attribute='ansible_host')
                 | unique
                 | map('ansible.utils.ipaddr') }}
  run_once: true
