---
- name: Ensure correct type for critical vars
  ansible.builtin.assert:
    that:
      - context.PASSWORD is undefined or context.PASSWORD is string
                                      or context.PASSWORD | type_debug == 'AnsibleVaultEncryptedUnicode'
      - one_pass is undefined or one_pass is string
                              or one_pass | type_debug == 'AnsibleVaultEncryptedUnicode'
                              or one_pass is none
      - one_token is undefined or one_token is string
                               or one_token | type_debug == 'AnsibleVaultEncryptedUnicode'
      - one_version is string
    fail_msg: Please make sure [context.PASSWORD, one_pass, one_token, one_version] are valid strings.

- name: Validate passwords strength
  ansible.builtin.assert:
    that: "{{ _items[item].that }}"
    fail_msg: >
      Password validation failed for "{{ item }}".
      {{ _items[item].fail_msg }}
  loop: "{{ _items.keys() | list }}"
  vars:
    _items:
      one_pass:
        condition: "{{ one_pass is defined }}"
        that:
          - one_pass | length > 0
          - not (one_pass | regex_search('[ \t\n\v\f\r]'))
          - one_pass not in ['opennebula', 'password']
        fail_msg: >
          Ensure the password meets the following criteria:
          - Must not be empty
          - Must not contain whitespace characters
          - Must not be trivial, one of ['opennebula', 'password']
      context.PASSWORD:
        condition: "{{ context is defined and context.PASSWORD is defined }}"
        that:
          - context.PASSWORD | length >= 8
          - context.PASSWORD | regex_search('[A-Z]')
          - context.PASSWORD | regex_search('[a-z]')
          - context.PASSWORD | regex_search('[0-9]')
          - context.PASSWORD | regex_search('[!@#$%^&*(),.?":{}|<>]')
        fail_msg: >
          Ensure the password meets the following criteria:
          - At least 8 characters long
          - Contains at least one uppercase letter
          - Contains at least one lowercase letter
          - Contains at least one digit
          - Contains at least one special character
  when:
    - prod_env | d(false) | bool is true
    - _items[item].condition
