---
one_pass: null
force_ha: false
force_master: false
unsafe_migrations: true
keep_empty_bridge: true
admin_pubkey: "{{ _admin_pubkey_loaded }}"
zone_name: "{{ ('OpenNebula' if (federation.role != 'SLAVE') else undef()) | mandatory('The zone_name var must be provided.') }}"
