---
- when:
    - ceph.repo is defined
    - ceph.repo == 'distro'
  tags: [preinstall]
  block:
    - name: Install extra Ceph/OpenNebula dependencies
      ansible.builtin.package:
        name: "{{ _common + _specific[ansible_os_family] }}"
      vars:
        _common: []
        _specific:
          Debian: [qemu-utils]
          RedHat: [qemu-img, "centos-release-ceph-{{ ceph_stable_release }}"]
      register: package
      until: package is success
      retries: 12
      delay: 5

- when:
    - ceph.repo is defined
    - ceph.repo == 'community'
  tags: [preinstall]
  block:
    - ansible.builtin.include_role:
        name: repository
      vars:
        repos_enabled: [ceph]
      when: ceph_repo is undefined

    - name: Install extra Ceph/OpenNebula dependencies
      ansible.builtin.package:
        name: "{{ _common + _specific[ansible_os_family] }}"
      vars:
        _common: []
        _specific:
          Debian: [qemu-utils]
          RedHat: [qemu-img]
      register: package
      until: package is success
      retries: 12
      delay: 5
