---
- name: Configure OneGate Server (:host)
  opennebula.deploy.cfgtool:
    dest: /etc/one/onegate-server.conf
    parser: Yaml
    actions:
      - put:
          path: [":host"]
          value: "{{ gate_bind_addr }}"
  notify:
    - Restart OneGate Server

# NOTE: ONEGATE_ENDPOINT is automatically propagated (as an environment variable)
#       to VMs that are expected to be using OneGate.
- name: Configure oned (ONEGATE_ENDPOINT)
  opennebula.deploy.cfgtool:
    dest: /etc/one/oned.conf
    parser: One
    actions:
      - put:
          path: [ONEGATE_ENDPOINT]
          value: '"{{ _gate_endpoint }}"'
  vars:
    _gate_endpoint: >-
      {{ gate_endpoint | d(_default) }}
    _default: >-
      {{ 'http://' ~ (one_vip | d(_host)) ~ ':5030' }}
    _host: >-
      {{ hostvars[federation.groups.frontend[0]].ansible_host }}
  notify:
    - Restart OpenNebula

- name: Configure TProxy
  opennebula.deploy.cfgtool:
    dest: /var/lib/one/remotes/etc/vnm/OpenNebulaNetwork.conf
    parser: Yaml
    actions:
      - put:
          path: [":tproxy"]
          value: "{{ gate_tproxy }}"
  notify:
    - Sync Remotes
  when: gate_tproxy is defined and gate_tproxy is sequence
