---
- name: Guess the Leader
  ansible.builtin.set_fact:
    leader: >-
      {{ one_vip | default(_frontend | random)
         if _frontend | length > 1 else
         _frontend[0] }}
  vars:
    _frontend: >-
      {{ groups[frontend_group | d('frontend')] }}
  run_once: true

- run_once: true
  block:
    - name: Decrement the retry counter
      ansible.builtin.set_fact:
        retry_no: >-
          {{ retry_no | default(6, true) | int - 1 }}

    - name: Ping the Leader
      ansible.builtin.wait_for:
        host: "{{ leader }}"
        port: "{{ ping_port | int }}"
        timeout: 10

    - name: Get Zone 0
      ansible.builtin.shell:
        cmd: onezone show 0 --json
        executable: /bin/bash
      register: shell
      changed_when: false
      delegate_to: "{{ leader }}"

    - name: Detect if the Leader is there
      ansible.builtin.set_fact:
        # Make sure the Leader isn't specifically the VIP, but
        # rather use its inventory_hostname (or the "SERVER[x].NAME").
        # This helps later when dealing with OneGate and OneFlow
        # services.
        leader: >-
          {{ _leader[0].NAME }}
      failed_when: _server_pool is truthy and _leader is falsy
      vars:
        _document: >-
          {{ shell.stdout | from_json }}
        _server_pool: >-
          {{ _document.ZONE.SERVER_POOL }}
        _peers: >-
          {{ [_server_pool.SERVER] | flatten | list }}
        _leader: >-
          {{ _peers | selectattr('STATE', '==', '3') | list }}
  rescue:
    - name: Abort after timeout
      ansible.builtin.fail:
      when: retry_no | int == 0

    - name: Pause for 10 seconds
      ansible.builtin.pause:
        seconds: 10

    - name: Continue the retry loop
      ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/main.yml"
