---
- name: Install dependencies (TRY)
  ansible.builtin.package:
    name: "{{ _common + _specific[ansible_os_family] }}"
  vars:
    _common: [ca-certificates, gnupg2]
    _specific:
      Debian: [apt-transport-https, dirmngr, software-properties-common]
      RedHat: []
  # NOTE: This allows for some limited recovery if re-executed, it is likely
  #       required packages are already installed.
  ignore_errors: true

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/{{ _item }}.yml"
  when:
    - repo_constraints[_item].condition
    - inventory_hostname in repo_constraints[_item].hosts
  loop: "{{ repos_enabled }}"
  loop_control: { loop_var: _item }

- name: Update package manager cache
  ansible.builtin.package:
    update_cache: "{{ _changed is any }}"
  vars:
    # Gather all existing results from repo config rendering.
    _changed: >-
      {{ repos_enabled | map('regex_replace', '^(.*)$', '\g<1>_repo')
                       | map('extract', hostvars[inventory_hostname], ['changed'])
                       | map('default', false) }}
