---
- name: Prevent Ceph deployment in the parallel federation deployment mode
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          (groups[_frontend_group ~ '0'] is undefined)
    msg: Please use sequential federation deployment mode if you want to deploy Ceph.
  vars:
    _frontend_group: "{{ frontend_group | d('frontend') }}"
  run_once: true

# We only support active Ceph releases (https://docs.ceph.com/en/latest/releases/index.html)
- name: Check if specified Ceph release is supported
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          ((ceph_stable_release is defined) and (ceph_stable_release in _supported))
    msg: Please specify one of the supported Ceph versions {{ _supported }} in ceph_stable_release variable.
  vars:
    _supported:
      - reef
      - squid
  tags: [preinstall]

# We only support active Ceph releases (https://docs.ceph.com/en/latest/releases/index.html)
# and recommended distro families (https://docs.ceph.com/en/latest/start/os-recommendations/)
# Other useful links:
# - https://sigs.centos.org/storage/general/
# - https://ubuntu.com/ceph/docs/supported-ceph-versions
- name: Check if Ceph feature is supported for current distro family
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          ((ceph_stable_release is defined) and (_repo in _repos))
    msg: Please use one of the supported linux distro families to run Ceph {{ ceph_stable_release | d('') }} version
         ({{ ansible_distribution }}/{{ ansible_distribution_major_version }}/{{ _repo }} combination is unsupported).
  vars:
    _repo: "{{ ceph.repo | d('community') }}"
    _repos: "{{ _supported[ceph_stable_release][ansible_distribution][ansible_distribution_major_version] }}"
    _supported:
      reef: # Ceph 18.2.z
        Debian:
          '11': [community]
          '12': [community]
        Ubuntu:
          '22': [distro, community]
        AlmaLinux:
          '9': [] # Not supported: https://tracker.ceph.com/issues/68802
        RedHat:
          '9': [] # Not supported: https://tracker.ceph.com/issues/68802
      squid: # Ceph 19.2.z
        Debian:
          '12': [community]
        Ubuntu:
          '20': [community]
          '22': [distro, community]
          '24': [distro]
        AlmaLinux:
          '9': [community]
        RedHat:
          '9': [community]
  tags: [preinstall]
