---
# We only support active Ceph releases (https://docs.ceph.com/en/latest/releases/index.html)
- name: Check if specified Ceph release is supported
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          ((ceph.release is defined) and (ceph.release in _supported))
    msg: Please specify one of the supported Ceph versions {{ _supported }} in ceph.release variable.
  vars:
    _supported:
      - squid
      - tentacle
  tags: [preinstall]

# We only support active Ceph releases (https://docs.ceph.com/en/latest/releases/index.html)
# and recommended distro families (https://docs.ceph.com/en/latest/start/os-recommendations/)
# Other useful links:
# - https://sigs.centos.org/storage/general/
# - https://ubuntu.com/ceph/docs/supported-ceph-versions
- name: Check if Ceph feature is supported for current distro family
  ansible.builtin.assert:
    that: (features.ceph is undefined)
          or
          (features.ceph | bool is false)
          or
          ((ceph.release is defined) and (_repo in _repos))
    msg: Please use one of the supported linux distro families to run Ceph {{ ceph.release | d('') }} version
         ({{ ansible_distribution }}/{{ ansible_distribution_major_version }}/{{ _repo }} combination is unsupported).
  vars:
    _repo: "{{ ceph.repo | d('community') }}"
    _repos: "{{ _supported[ceph.release][ansible_distribution][ansible_distribution_major_version] }}"
    _supported:
      squid: # Ceph 19.2.z
        Debian:
          '12': [community]
          '13': []
        Ubuntu:
          '22': [community]
          '24': [distro]
        AlmaLinux:
          '9': [community]
          '10': []
        RedHat:
          '9': [community]
          '10': []
        openSUSE Leap:
          '16': []
      tentacle: # Ceph 20.2.z
        Debian:
          '12': [community]
          '13': []
        Ubuntu:
          '22': [community]
          '24': []
        AlmaLinux:
          '9': [community]
          '10': []
        RedHat:
          '9': [community]
          '10': []
        openSUSE Leap:
          '16': []
  tags: [preinstall]
