---
- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/ceph.yml"
  vars:
    _hosts: >-
      {{ (groups.get(node_group | d('node'), []) + groups.get(mon_group_name | d('mons'), [])
                                                 + groups.get(mgr_group_name | d('mgrs'), [])
                                                 + groups.get(osd_group_name | d('osds'), [])) | unique }}
  when: inventory_hostname in _hosts

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/site.yml"
  vars:
    _hosts: >-
      {{ (groups.get(node_group | d('node'), []) + groups.get(frontend_group | d('frontend'), [])) | unique }}
  when: inventory_hostname in _hosts

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/pci_passthrough.yml"
  vars:
    _hosts: >-
      {{ groups.get(node_group | d('node'), []) }}
  when: inventory_hostname in _hosts
