---
- name: Provision Datastores (node)
  ansible.builtin.include_role:
    name: "datastore/{{ _mode_to_role[ds.mode] }}"
    tasks_from: node
  vars:
    _mode_to_role:
      ssh: simple
      ceph: simple
      shared: simple
      generic: generic
  when:
    - ds.mode is defined
