---
- name: &name "datastore/{{ _mode_to_role[ds.mode] }}"
  ansible.builtin.include_role:
    name: *name
  vars:
    _target_group: >-
      {{ node_group | d('node') }}
    _mode_to_role:
      ssh: simple
      qcow2: simple
      shared: simple
      generic: generic
