---
- when: _fstab | count > 0
  vars:
    # Merge with defaults.
    _fstab: >-
      {{
        ({} | combine(
          range(fstab | count) | zip ((fstab | count) * [fstab_defaults])
                               | items2dict(key_name=0, value_name=1),
          range(fstab | count) | zip(fstab)
                               | items2dict(key_name=0, value_name=1),
          recursive=true,
        )).values()
      }}
  block:
    - name: Assert that fstab structure has all required fields
      ansible.builtin.assert:
        that: _fstab == _fstab | selectattr('src', 'defined')
                               | selectattr('path', 'defined')
                               | selectattr('fstype', 'defined')
        fail_msg: Fields 'src', 'path' and 'fstype' are strictly required.
                  Please make sure to define them.

    - name: Install required OS packages
      ansible.builtin.package:
        name: "{{ (_common + _specific[ansible_os_family]) | select }}"
      vars:
        _common: [util-linux]
        _specific:
          Debian:
            - "{{ 'nfs-common' if ('nfs' in _fstypes) else none }}"
          RedHat:
            - "{{ 'nfs-utils' if ('nfs' in _fstypes) else none }}"
          Suse:
            - "{{ 'nfs-client' if ('nfs' in _fstypes) else none }}"
        _fstypes: >-
          {{ _fstab | map(attribute='fstype')
                    | map('lower') }}
      register: package
      until: package is success
      retries: 12
      delay: 5

    - name: Assert that fstab config matches existing filesystems
      ansible.builtin.shell:
        cmd: |
          set -o errexit
          FAILED=false
          {% for v in _fstab %}
          if TYPE="$(blkid -o value -s TYPE '{{ v.src }}')"; then
            if [[ "$TYPE" != '{{ v.fstype }}' ]]; then
              echo "Filesystem type on device '{{ v.src }}' does not match requested fstab config ('$TYPE' != '{{ v.fstype }}')." >&2
              echo 'Please consider fixing this problem manually before continuing.' >&2
              FAILED=true
            fi
          fi
          {% endfor %}
          if [[ "$FAILED" == true ]]; then
            exit 1
          fi
        executable: /bin/bash
      changed_when: false

    # NOTE: All intermediate subdirectories will be created if they do not exist.
    #       Since Ansible 1.7 they will be created with the supplied permissions.
    - name: Ensure mountpoints with desired permissions exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner | default(omit, true) }}"
        group: "{{ item.group | default(omit, true) }}"
        mode: "{{ item.mode | default(omit, true) }}"
        state: directory
      loop: "{{ _fstab }}"

    - name: Add to fstab and mount filesystems
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        state: mounted
      loop: "{{ _fstab }}"
