---

- name: Run throughput tests
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/iperf.yml"
  when: iperf.run

- name: Run RTT tests
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/ping.yml"
  when: ping.run

# tasks/main.yml
- name: Run network tests
  when: item.run
  block:
    - name: Ensure results directory exists
      ansible.builtin.file:
        path: "{{ item.results_path }}"
        state: directory
        recurse: true
      delegate_to: localhost
      become: false

    - name: Include test tasks
      ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/{{ item.task_file }}"
      vars:
        current_test: "{{ item }}"
  loop: "{{ network_tests }}"
