---
- when: pci_passthrough_enabled | bool is true
  block:
    - ansible.builtin.include_role:
        name: opennebula.deploy.helper.pci
      when:
        - lspci_devices is undefined

    - ansible.builtin.import_tasks:
        file: "{{ role_path }}/tasks/filters.yml"
      when:
        - lspci_devices is defined
        - lspci_devices is sequence
        - lspci_devices | count > 0
