---
- when: pci_passthrough_enabled | bool is true
  block:
    - ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/devices.yml"
      when:
        - pci_devices is defined
        - pci_devices is sequence
        - pci_devices | count > 0

    - ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/filters.yml"
      when:
        - pci_devices_by_vendor_device_class is defined
        - pci_devices_by_vendor_device_class is sequence
        - pci_devices_by_address is defined
        - pci_devices_by_address is sequence
        - ((pci_devices_by_vendor_device_class | count) + (pci_devices_by_address | count)) > 0
