---
- when: _enabled is true
  vars:
    _enabled: >-
      {{ _hosts | map('extract', hostvars)
                | map(attribute='pci_devices', default=[])
                | select
                | count > 0 }}
    _hosts: >-
      {{ groups[node_group | d('node')] }}
  block:
    - name: Apply global PCI filter
      opennebula.deploy.cfgtool:
        dest: /var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf
        parser: Yaml
        actions:
          - put:
              path: [":filter"]
              value: "{{ pci_default_filter }}"
      notify:
        - Sync Remotes
