---
- name: Copy view folder
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/views/{{ sunstone_view_source_folder }}/"
    dest: "{{ sunstone_views_base_dir }}{{ sunstone_view_name }}/"
    mode: u=rw,g=r,o=r

- name: Update views definition in sunstone-views.yaml
  opennebula.deploy.cfgtool:
    dest: "{{ sunstone_views_config_file }}"
    parser: Yaml
    actions:
      - put:
          path: [views, "{{ sunstone_view_name }}"]
          value:
            name: "{{ sunstone_view_label }}"
            description: "{{ sunstone_view_description }}"

- name: Add view to groups in sunstone-views.yaml
  opennebula.deploy.cfgtool:
    dest: "{{ sunstone_views_config_file }}"
    parser: Yaml
    actions:
      - get:
          path: [groups, "{{ item }}"]
  register: _groups_cfg
  loop: "{{ sunstone_view_groups }}"
  changed_when: false

- name: Update group views list
  opennebula.deploy.cfgtool:
    dest: "{{ sunstone_views_config_file }}"
    parser: Yaml
    actions:
      - put:
          path: [groups, "{{ item.item }}", 0]
          value: "{{ sunstone_view_name }}"
  loop: "{{ _groups_cfg.results }}"
  # item.values[0] is the list of views for the group
  when: sunstone_view_name not in item['values'][0]
