---
node_hypervisor: kvm # currently "kvm" only

alertmanager_config: |
  ---
  global:
    resolve_timeout: 5m

  route:
    group_by: [alertname]
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 1h
    receiver: discard

  receivers:
    - name: discard

  templates: []

  inhibit_rules:
    - source_match:
        severity: critical
      target_match:
        severity: warning
      equal: [alertname, dev, instance]

grafana_repo_key_path:
  Debian: /etc/apt/trusted.gpg.d/grafana.asc
  RedHat: /etc/pki/rpm-gpg/RPM-GPG-KEY-grafana

grafana_repo_key_url:
  Debian: https://apt.grafana.com/gpg.key
  RedHat: https://rpm.grafana.com/gpg.key

grafana_repo_path:
  Debian: /etc/apt/sources.list.d/grafana.list
  RedHat: /etc/yum.repos.d/grafana.repo

grafana_repo_url:
  Debian: https://apt.grafana.com
  RedHat: https://rpm.grafana.com
