---
- vars:
    _if_to_con: >-
      {{ command_con_show.stdout_lines | map('split', ':')
                                       | selectattr(0, 'in', [_phydev, _bridge])
                                       | items2dict(key_name=0, value_name=1) }}

    _con_to_kv: >-
      {%- set output = {} -%}
      {%- for item in command_con_show_details.results -%}
        {%- for line in item.stdout_lines -%}
          {%- set k, v = line.split(':', 1) -%}
          {%- if k.startswith('ipv') -%}
            {{- output.update(output | combine({item.item: {k: v}}, recursive=true)) -}}
          {%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{- output -}}

    _should_create_bridge: >-
      {{ (_phydev in _if_to_con)
         and
         (_bridge not in _if_to_con) }}

    # NOTE: We leave the bridge alone if it already has an IP address assigned,
    #       as we must not override any existing user config.
    #       A coincidence here is that this serves as an idempotence guard and the
    #       done condition at the same time.
    _should_update_bridge: >-
      {{ (_bridge in _if_to_con)
         and
         ([ _con_to_kv[_if_to_con[_bridge]].get('ipv4.addresses', '')
          , _con_to_kv[_if_to_con[_bridge]].get('ipv6.addresses', '') ] is not any) }}
  block:
    - &collect
      block:
        - name: Map PHYDEV -> CON (get)
          ansible.builtin.command:
            cmd: nmcli --terse -f DEVICE,NAME con show --active
          changed_when: false
          register: command_con_show

        - name: Map CON -> KV (get)
          ansible.builtin.command:
            cmd: nmcli --terse con show '{{ item }}'
          loop: >-
            {{ _if_to_con.values() }}
          changed_when: false
          register: command_con_show_details

    - when: _should_create_bridge
      block:
        - name: Create a bridge using NetworkManager's CLI
          ansible.builtin.command:
            cmd: nmcli con add type bridge ifname '{{ _bridge }}'
          changed_when: true

    - *collect

    - when: _should_update_bridge
      block:
        - name: Copy IP4/6 settings PHYDEV -> BRIDGE (set)
          ansible.builtin.command:
            cmd: nmcli con modify '{{ _if_to_con[_bridge] }}' {{ _args }}
          changed_when: true
          vars:
            _args: >-
              {{ _con_to_kv[_if_to_con[_phydev]].items() | flatten
                                                         | map('regex_replace', '^(.*)$', " '\g<1>'")
                                                         | join }}

        # NOTE: It looks like modern releases of NM clean up PHYDEV automatically.
        - name: Move PHYDEV -> BRIDGE (set)
          ansible.builtin.command:
            cmd: nmcli con modify '{{ _if_to_con[_phydev] }}' master '{{ _bridge }}' slave-type bridge
          changed_when: true

        - name: Apply config using NetworkManager's CLI
          ansible.builtin.command:
            cmd: nmcli con up '{{ item }}'
          loop:
            - "{{ _if_to_con[_bridge] }}"
            - "{{ _if_to_con[_phydev] }}"
          changed_when: true
