---
- name: Compute facts
  ansible.builtin.set_fact:
    features: >-
      {{ features_defaults | combine(features | d({})) }}
    federation:
      # Decide what role should this Front-end perform.
      role: >-
        {{ 'MASTER'
           if (_force_master or (_subgroup == (_frontend_group ~ '0'))) else
           'SLAVE'
           if ((groups[_federation_group] is defined) or (_subgroup != _frontend_group)) else
           'STANDALONE' }}
      # The (sub)group to which this Front-end is added.
      group_name: "{{ _subgroup }}"
      # Complete set of groups that describe this federated Front-end.
      groups:
        all: >-
          {{ (groups[_frontend_group ~ _index] + groups[_node_group ~ _index]) | unique }}
        frontend: >-
          {{ groups[_frontend_group ~ _index] }}
        node: >-
          {{ groups[_node_group ~ _index] }}
      # Points to the leader of the master Front-end.
      # NOTE: This handles both federation deployment modes, "parallel" and "sequential".
      master: >-
        {{ (hostvars[_leader].one_vip | d(hostvars[_leader].ansible_host))
           if (_leader is defined) else
           hostvars[_master].ansible_host }}
  vars:
    # The inferred master machine.
    _master: >-
      {{ groups[_federation_group] | d(groups[_frontend_group ~ '0'])
                                   | d(groups[_frontend_group])
                                   | first }}
    _leader: >-
      {{ hostvars[_master].leader }}
    # The index of this Front-end (group).
    _index: >-
      {{ [_subgroup] | map('regex_search', _regex)
                     | select
                     | map('regex_replace', _regex, '\g<2>')
                     | first
                     | d('') }}
    # This Front-end (group).
    _subgroup: >-
      {{ group_names | map('regex_search', _regex)
                     | select
                     | map('regex_replace', _regex, (_frontend_group ~ '\g<2>'))
                     | unique
                     | first
                     | d(_frontend_group) }}
    # Helper vars.
    _regex: >-
      {{ '^' ~ '(' ~ _frontend_group ~ '|' ~ _node_group ~ ')' ~ '(\d+)' ~ '$' }}
    _frontend_group: >-
      {{ frontend_group | d('frontend') }}
    _node_group: >-
      {{ node_group | d('node') }}
    _federation_group: >-
      {{ federation_group | d('federation') }}
    # NOTE: This is used only in "sequential" federation deployment mode (to prepare the
    #       master Front-end to handle subsequent slave Front-end additions).
    _force_master: >-
      {{ (force_master is defined) and (force_master | bool) is true }}

- name: Compute facts (Ceph)
  ansible.builtin.set_fact:
    ceph: >-
      {{ ceph_defaults | combine(ceph | d({})) }}
  when: features.ceph | bool is true
