---
- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/params.yml"
  when:
    - kernel_params is defined
    - kernel_params is sequence
    - kernel_params | count > 0

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/modules.yml"
  when:
    - kernel_modules is defined
    - kernel_modules is sequence
    - kernel_modules | count > 0

- when:
    - kernel_ok_to_reboot | bool is true
    - kernel_need_to_reboot | bool is true
  block:
    - name: Reboot (NOW)
      ansible.builtin.reboot: {}

    - name: Re-gather facts after reboot
      ansible.builtin.include_role:
        name: opennebula.deploy.helper.facts
      vars: { _force: true }
