---
- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/params.yml"
  when:
    - kernel_params is defined
    - kernel_params is sequence
    - kernel_params | count > 0

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/modules.yml"
  when:
    - kernel_modules is defined
    - kernel_modules is sequence
    - kernel_modules | count > 0

- name: Reboot (NOW)
  ansible.builtin.reboot: {}
  when:
    - kernel_ok_to_reboot | bool is true
    - kernel_need_to_reboot | bool is true
