---
iperf:
  run: true
  port: 5201
  test_time: 10
  results_path: "{{ benchmark_results_path }}/{{ inventory_hostname }}/network/iperf"
ping:
  run: true
  test_time: 10
  results_path: "{{ benchmark_results_path }}/{{ inventory_hostname }}/network/ping"
