---
- hosts:
    - "{{ mon_group | d('mon') }}"
    - "{{ mgr_group | d('mgr') }}"
    - "{{ osd_group | d('osd') }}"
  tags: [ceph]
  collections:
    - opennebula.deploy
  roles:
    # This installs the interpreter only.
    # Extra OS/PyPI packages should not required by this playbook.
    - role: helper/python3

    - role: helper/facts
      tags: [always]

    - role: ceph/repository
    - role: ceph/cephadm
