---
- name: Enable passthrough in the hosts
  tags: [passthrough,node]
  hosts:
    - "{{ node_group | d('node') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
    - role: passthrough/node

# 1. Identify the device(s) to passthrough. Look only for Nvidia GPUs for now, and store their device ID, vendor ID, and PCI address.
# 2. Check cpu architecture, and verify (again) if virtualization is enabled
#    If disabled, playbook stops
#   - In intel, search flags for vmx and ept
#   - In amd, search flags for svm and npt
#   - If not x86_64, stop playbook, passthrough not supported
# 3. Check cpu architecture, and verify if IOMMU is enabled
#    If enabled, skip to step 5
#   - Run 'dmesg | grep -i -e DMAR -e IOMMU -e AMD-Vi'
#   - Search for string 'DMAR: IOMMU enabled'
#   - Parse and save lines like "[    1.624973] pci 0000:5d:00.0: Adding to iommu group 0" if they appear.
# 4. Enable IOMMU in the kernel
#   - For intel, add "intel_iommu=on" to the kernel command line
#   - For amd, add "amd_iommu=on" to the kernel command line (they say its unnecessary, idk)
#   - For both, add "iommu=pt" to the kernel command line (unchecked improvements, but it works)
#   - Study if disabling MSR (Model-Specific Register) due to error doing passthrough to Windows VMs.
#   - Reboot the host
# 5. Validate each passtrhough device has a separate IOMMU group. If not, error? the ACS Override Patch?? (MoBo must support it)
# 6. Check if the devices are in use. If so, error
# 7. Check if the devices (and all devices from same IOMMU group) are bound to vfio-pci.
#    If bounded, skip to step 8
#   - Check if the vfio-pci module is loaded. If not, modprobe it
#   - Override the device's default driver with vfio-pci
#   - Blacklist the nouveau/nvidia drivers
#   - Reboot the host
#   - Repeat step
# 8. Add udev rule so that libvirt can use vfio devices


- name: Enable passthrough for Nvidia GPUs
  tags: [passthrough,frontend]
  hosts:
    - "{{ node_group | d('frontend') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
    - role: passthrough/frontend


# 1. Edit /var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf with:
# :filter:
#     - '10de:*'
# 2. Install VM from active FE
