---
- name: Enable passthrough functionalities in OpenNebula
  hosts: all 
  tags: [passthrough, node, frontend]
  collections:
    - opennebula.deploy
  roles:
    # - role: helper/facts
    #   tags: [always]

    # # Make sure all facts are usable on the playbook level.
    # - role: common

    # # The repository role can be safely executed on the whole inventory, it will auto-detect
    # # which types of repositories it should install on which hosts.
    # - role: repository
    #   tags: [preinstall, prometheus]

    - role: passthrough

# si linea está puesta
# DMAR: IOMMU enabled
# si está funcionando
# DMAR: Intel(R) Virtualization Technology for Directed I/O



# -------------------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------- NODES -----------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------------------------------

# 1. Check the node's CPU and perform some initial assessments. If they fail, passthrough is not available for the node
#   - Verify CPUs have x86_64 architecture.
#   - In intel CPUs, verify flags 'vmx' and 'ept'
#   - In AMD CPUs, verify flags 'svm' and 'npt'
#
# 2. Enable IOMMU in the kernel.
#   - Verify if IOMMU is already enabled from dmesg. If so, skip to step 5.
#   - For intel, add "intel_iommu=on iommu=pt" to the kernel command line.
#   - For AMD, add "iommu=pt" to the kernel command line.
#   - Reconfig GRUB and reboot
#   - Verify again that IOMMU is enabled in all hosts
#
# 3. Add udev rule so that libvirt (oneadmin:kvm)  can use vfio devices
#
#### FOCUSING ON NVIDIA GPUs ####
# 4. Identify hosts with NVIDIA GPU's and theirthe device(s) to passthrough. Look only for Nvidia GPUs for now, and store their device ID, vendor ID, and PCI address
# 5. If vfio modules are not loaded, load them.
# 6. If nvidia and nouveau modules are loaded, blacklist them.
# 7. If the GPUs are not bound to vfio-pci, bind them.
# 8. Update the initramfs and reboot the node.

# Aditional checks:
# - Validate each passtrhough device has a separate IOMMU group. If not, error? the ACS Override Patch?? (MoBo must support it)
# - Check if the devices are in use before manipulating their drivers.


# -------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------- FRONTENDS -----------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------------------------------

# 1. Edit /var/lib/one/remotes/etc/im/kvm-probes.d/pci.conf with:
# :filter:
#     - '10de:*'
# 2. Install VM from active FE
