---
- hosts:
    - "{{ bastion_group | d('bastion') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: bastion
      delegate_to: localhost
      become: false
      tags: [bastion]

# Cluster integrity / consistency.

- hosts:
    - "{{ router_group | d('router') }}"
    - "{{ frontend_group | d('frontend') }}"
    - "{{ node_group | d('node') }}"
    - "{{ grafana_group | d('grafana') }}"
    - "{{ mon_group_name | d('mons') }}"
    - "{{ mgr_group_name | d('mgrs') }}"
    - "{{ osd_group_name | d('osds') }}"
  strategy: linear
  collections:
    - opennebula.deploy
  roles:
    - role: helper/python3 # for python intepreter

    - role: helper/facts

    - role: helper/cache

    - role: helper/python3 # for extra OS/PyPI packages

- hosts:
    - "{{ frontend_group | d('frontend') }}"
    - "{{ node_group | d('node') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: helper/hosts
      tags: [hosts]

- hosts:
    - "{{ frontend_group | d('frontend') }}"
    - "{{ node_group | d('node') }}"
    - "{{ mon_group_name | d('mons') }}"
    - "{{ mgr_group_name | d('mgrs') }}"
    - "{{ osd_group_name | d('osds') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
      tags: [always]

    - role: precheck/pre_reboot

- hosts:
    - "{{ frontend_group | d('frontend') }}"
    - "{{ node_group | d('node') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: helper/keys
      tags: [keys]

    - role: helper/ntp
      tags: [ntp]

    - role: helper/logs
      tags: [logs]

    - role: helper/mkfs
      tags: [mkfs]

    - role: helper/fstab
      tags: [fstab]

    - role: helper/kernel
      tags: [kernel]

    - role: precheck/post_reboot

# Early PCI/SR-IOV + OVS/DPDK management.

- hosts:
    - "{{ node_group | d('node') }}"
  collections:
    - opennebula.deploy
  roles:
    # NOTE: PCI/SR-IOV management is limited to HV nodes exclusively.
    - role: helper/pci
      tags: [pci, pci_passthrough]

- hosts:
    - "{{ frontend_group | d('frontend') }}"
    - "{{ node_group | d('node') }}"
  collections:
    - opennebula.deploy
  roles:
    # NOTE: This is required here since OVS/DPDK may require custom package sources.
    - role: repository
      tags: [openvswitch]

    - role: openvswitch
      tags: [openvswitch]
