---
- hosts: "{{ frontend_group | d('frontend') }}"
  tags: [frontend, stage1]
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
      tags: [always]

    # Make sure all facts are usable on the playbook level.
    - role: common

    - role: repository
      tags: [preinstall, prometheus]

    - role: database
    - role: opennebula/server
    - role: gate/server
      tags: [gate]

    # Wait until the Leader is elected, then run handlers (and possibly restart all oned instances),
    # then wait until the cluster is stable again. NOTE: After all that we make sure not to restart
    # OpenNebula services until the end of the playbook!
    - role: opennebula/leader
    - role: helper/flush
    - role: opennebula/leader

    - role: flow
      tags: [flow]

    - role: gui
      tags: [gui]

- hosts: "{{ router_group | d('router') }}"
  tags: [network]
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
      tags: [always]

    # Make sure all facts are usable on the playbook level.
    - role: common

    - role: frr/evpn
      when: &evpn
        - features.evpn | bool is true

- hosts: "{{ node_group | d('node') }}"
  tags: [node, stage2]
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
      tags: [always]

    # Make sure all facts are usable on the playbook level.
    - role: common

    - role: repository
      tags: [preinstall, prometheus]

    - role: kvm

    - role: ceph/node
      tags: [ceph]
      when:
        - features.ceph | bool is true

    - role: datastore/node
      tags: [datastore]

    - role: frr/evpn
      tags: [network]
      when: *evpn

    - role: network/node
      tags: [network]

    - role: gate/proxy
      tags: [gate]
      when:
        - features.gateproxy | bool is true

    - role: prometheus/exporter
      tags: [prometheus]
      when: &prometheus
        - features.prometheus | bool is true
        - one_token is defined and one_token is truthy

- hosts: "{{ frontend_group | d('frontend') }}"
  tags: [frontend, stage3]
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
      tags: [always]

    # Make sure all facts are usable on the playbook level.
    - role: common

    - role: ceph/frontend
      tags: [ceph]
      when:
        - features.ceph | bool is true

    - role: datastore/frontend
      tags: [datastore]

    - role: network/frontend
      tags: [network]

    - role: prometheus/server
      tags: [prometheus]
      when: *prometheus

- hosts: "{{ grafana_group | d('grafana') }}"
  collections:
    - opennebula.deploy
  roles:
    - role: helper/facts
      tags: [always]

    # Make sure all facts are usable on the playbook level.
    - role: common

    - role: repository
      tags: [preinstall, grafana]

    - role: prometheus/grafana
      tags: [grafana]
      when: *prometheus
