---
ds:
  mode: ssh
  config: {}

ds_defaults:
  ssh:
    SYSTEM_DS:
      template:
        TM_MAD: ssh
    IMAGE_DS:
      template:
        TM_MAD: ssh
    FILE_DS:
      template:
        TM_MAD: ssh
  ceph:
    SYSTEM_DS:
      template:
        TM_MAD: ceph
        POOL_NAME: "{{ ceph.pool if features.ceph is true else None }}"
        CEPH_HOST: "{{ ceph.host if features.ceph is true else None }}"
        CEPH_USER: "{{ ceph.user if features.ceph is true else None }}"
        CEPH_SECRET: "{{ ceph.uuid if features.ceph is true else None }}"
        BRIDGE_LIST: "{{ groups[node_group | d('node')] | map('extract', hostvars, ['ansible_host']) | join(' ') }}"
    IMAGE_DS:
      template:
        TM_MAD: ceph
        DS_MAD: ceph
        DISK_TYPE: RBD
        POOL_NAME: "{{ ceph.pool if features.ceph is true else None }}"
        CEPH_HOST: "{{ ceph.host if features.ceph is true else None }}"
        CEPH_USER: "{{ ceph.user if features.ceph is true else None }}"
        CEPH_SECRET: "{{ ceph.uuid if features.ceph is true else None }}"
        BRIDGE_LIST: "{{ groups[node_group | d('node')] | map('extract', hostvars, ['ansible_host']) | join(' ') }}"
    FILE_DS:
      template:
        TM_MAD: ssh
  shared:
    SYSTEM_DS:
      template:
        TM_MAD: shared
        BRIDGE_LIST: "{{ groups[node_group | d('node')] | map('extract', hostvars, ['ansible_host']) | join(' ') }}"
    IMAGE_DS:
      template:
        TM_MAD: shared
    FILE_DS:
      template:
        TM_MAD: ssh
